CREATE TABLE DAON(
	SEQ NUMBER,
	ID VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(20)NOT NULL,
	NAME VARCHAR2(100)NOT NULL,
	ADDRESS VARCHAR2(100)NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL);

CREATE SEQUENCE DAON_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE DAON DROP CONSTRAINT DAON_PK;
ALTER TABLE DAON ADD CONSTRAINT DAON_PK PRIMARY KEY (ID);

--ID중복체크--
SELECT ID FROM DAON WHERE ID='admin';

--회원가입--
INSERT INTO DAON(ID,PASSWORD,NAME,ADDRESS,PHONE,EMAIL)
VALUES('admin','admin','관리자','다온집','다온폰','다온@gmail.com');